In [1]:
import pandas as pd
import pypsa
import numpy as np
network = pypsa.Network()

In [3]:
buses= pd.read_csv('data/base_grid/bus.csv')
load = pd.read_csv('data/base_grid/demand.csv')
load

,UTC Time,1,2,3,4,5,6,7,8,9,...,215,216,301,302,303,304,305,306,307,308
0,2016-01-01 00:00:00,1342.820998,1440.655575,600.763115,7581.562212,910.213388,4209.789191,13681.797134,6569.102877,11711.598199,...,1766.755706,606.156577,2173.808470,868.636393,1229.206403,3340.356277,13411.928150,6312.753451,10703.575700,1341.750663
1,2016-01-01 01:00:00,1276.779250,1369.802192,571.235771,7208.690759,865.447866,4003.605235,13191.207415,6330.134845,11365.838316,...,1893.956134,677.637306,2206.959175,890.950782,1269.137961,3434.009672,13768.250380,6567.961704,10743.720990,1449.531975
2,2016-01-01 02:00:00,1217.843260,1306.572273,544.883366,6875.938387,825.498888,3819.512768,12731.366373,6107.739910,11008.828130,...,1900.987874,706.229597,2200.797530,873.920708,1252.891804,3325.388189,13413.202230,6410.274352,10436.555930,1355.505824
3,2016-01-01 03:00:00,1157.820508,1242.176413,518.037295,6537.050155,784.813262,3631.675821,12197.977055,5847.180918,10644.098537,...,1861.179030,685.500186,2179.300089,860.342391,1234.948091,3178.545879,13004.190740,6186.765392,10117.139850,1314.445489
4,2016-01-01 04:00:00,1095.791423,1175.628045,490.295684,6186.834183,742.767670,3437.642565,11661.265811,5585.914682,10259.253684,...,1816.505706,664.055967,2154.405686,840.608568,1215.899839,3054.399972,12578.409750,5919.270362,9836.114934,1330.866082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,2016-12-31 19:00:00,1230.215638,1319.846072,550.369002,6945.792786,833.885340,3856.056040,12429.077975,5949.512441,10999.286349,...,1772.381954,573.275442,2047.459060,690.662724,972.530847,2753.507565,10261.647950,5224.348142,9651.340702,1142.804232
8780,2016-12-31 20:00:00,1230.048444,1319.666696,550.293181,6944.848807,833.772010,3855.485732,12426.952472,5944.369109,11080.122343,...,1731.517475,574.705057,2035.036805,675.302580,956.366342,2786.112487,10060.687810,5172.488289,9639.117255,1125.266863
8781,2016-12-31 21:00:00,1251.031328,1342.178341,559.677808,7063.318092,847.994979,3921.137495,12608.057271,6034.159310,11177.281775,...,1694.259986,563.982948,2026.887979,668.133067,952.481990,2824.326084,9993.343749,5227.405904,9637.841629,1124.054410
8782,2016-12-31 22:00:00,1337.219989,1434.646491,598.217981,7549.938937,906.416818,4190.452183,13270.892083,6368.153248,11422.326718,...,1663.710057,563.982948,2023.906935,674.449005,954.350079,2854.735119,10078.584950,5306.905485,9683.466597,1118.782875
8783,2016-12-31 23:00:00,1396.239575,1497.966097,624.635493,7883.163299,946.422462,4376.059835,13989.908336,6713.478299,12039.420790,...,1670.215763,555.405260,2032.573815,705.708943,976.030421,2914.223617,10665.671250,5540.721708,10066.856620,1176.701108